version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DIALECT: postgres
      DB_PORT: 5432
      DB_NAME: spring
      DB_USER: springuser
      DB_PASSWORD: springpw
      BUCKET_HOST: minio
      BUCKET_PORT: 9000
      BUCKET_ACCESS_KEY: minioadmin
      BUCKET_ACCESS_SECRET: minioadminpw
      BUCKET_NAME: files
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - db
      - minio

  db:
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: spring
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpw
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres
    networks:
      - app

  minio:
    image: bitnami/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpw
      MINIO_DEFAULT_BUCKETS: files
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - app

volumes:
  db-data:
  minio:

networks:
  app:
