name: Upload JAR to Releases

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Project as jar file
        run: mvn -B package --file pom.xml

      - run: mkdir -p download && cp target/*.jar download
      - name: Upload JAR to as Artifact to Actions/Workflow
        uses: actions/upload-artifact@v4
        with:
          name: ParkPalBackend
          path: download
