name: Upload JAR to Releases

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: mvn -B package --file pom.xml

      - name: Upload JAR to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/spring-rest-backend-0.0.1.jar
          tag_name: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: osama004/ParkPal-Backend
