name: Upload JAR to Releases

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven
        run: mvn -B package --file pom.xml

      - run: mkdir -p download && cp target/*.jar download
      - name: Upload JAR to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: ParkPalBackend
          path: download
